version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://bitebase:bitebase@db:5432/bitebase
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=bitebase
      - POSTGRES_PASSWORD=bitebase
      - POSTGRES_DB=bitebase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
